FROM stepankuzmin/pytorch-notebook

ENV PATH /opt/conda/bin:$PATH
# This must be done before pip so that requirements.txt is available
RUN /opt/conda/bin/conda config --set ssl_verify False

ADD ./mnist_DDP.py /opt/pytorch_dist_mnist/
